/**
 * data.js — Contenu du fan-site JoJo's Bizarre Adventure
 * Toutes les données sont regroupées ici pour être modifiées facilement
 * sans toucher à la logique de l'application (js/app.js).
 *
 * Note : les statistiques de Stand suivent l'échelle officielle A → E
 * (Puissance, Vitesse, Portée, Persistance, Précision, Potentiel) telle
 * qu'utilisée par Hirohiko Araki dans les fiches de Stand. Elles sont
 * données ici à titre indicatif / approximatif.
 */

const JJBA_DATA = {
  meta: {
    titre: "JOJO'S BIZARRE ADVENTURE",
    sousTitre: "Encyclopédie interactive de l'univers JoJo",
    auteur: "Hirohiko Araki",
    premierePublication: 1987,
    magazine: "Weekly Shōnen Jump → Ultra Jump",
    studioAnime: "David Production",
    partiesPubliees: 9,
  },

  /** Les 9 parties de la saga, dans l'ordre de publication. */
  parties: [
    {
      id: "part1",
      numero: 1,
      titre: "Phantom Blood",
      titreJp: "ファントムブラッド",
      publication: "1987",
      epoque: "1880 – 1889",
      lieu: "Angleterre",
      jojo: "Jonathan Joestar",
      antagoniste: "Dio Brando",
      pouvoir: "Hamon (Onde)",
      couleur: "#8c1c3a",
      accroche: "Là où tout commence : l'onde contre l'ambition d'un vampire.",
      resume:
        "Jonathan Joestar, héritier idéaliste du domaine Joestar, voit sa vie brisée par Dio Brando, un orphelin recueilli par son père. Devenu vampire grâce à un antique Masque de Pierre, Dio oblige Jonathan à apprendre le Hamon pour protéger sa famille et l'humanité.",
      themes: ["Hamon", "Vampires", "Masque de Pierre", "Honneur"],
      casting: ["Jonathan Joestar", "Dio Brando", "Erina Pendleton", "Will A. Zeppeli", "Robert E. O. Speedwagon", "Tonpetty", "Dire", "Straizo"],
      note: "Le dernier combat sur le bateau à vapeur reste l'un des plus emblématiques du manga.",
    },
    {
      id: "part2",
      numero: 2,
      titre: "Battle Tendency",
      titreJp: "戦闘潮流",
      publication: "1987 – 1989",
      epoque: "1938 – 1939",
      lieu: "États-Unis, Mexique, Italie, Suisse",
      jojo: "Joseph Joestar",
      antagoniste: "Kars (et les Pillar Men)",
      pouvoir: "Hamon (Onde)",
      couleur: "#c2570a",
      accroche: "Le JoJo le plus roublard face aux créateurs du Masque.",
      resume:
        "Joseph Joestar, petit-fils de Jonathan, part affronter les Pillar Men, des êtres antiques à l'origine des Masques de Pierre. Bluffeur et imprévisible, il compense sa fougue par un sens tactique hors norme.",
      themes: ["Hamon", "Pillar Men", "Esidisi", "Wamuu", "Kars", "Santana"],
      casting: ["Joseph Joestar", "Caesar Anthonio Zeppeli", "Lisa Lisa", "Rudol von Stroheim", "Esidisi", "Wamuu", "Kars", "Santana"],
      note: "Joseph deviendra le doyen de la famille Joestar et apparaîtra jusqu'à la partie 4.",
    },
    {
      id: "part3",
      numero: 3,
      titre: "Stardust Crusaders",
      titreJp: "スターダストクルセイダース",
      publication: "1989 – 1992",
      epoque: "1988 – 1989",
      lieu: "Japon, Asie, Moyen-Orient, Égypte",
      jojo: "Jotaro Kujo",
      antagoniste: "DIO",
      pouvoir: "Stands (introduits ici)",
      couleur: "#3b3f8f",
      accroche: "La partie qui a fait exploser la popularité mondiale de la saga.",
      resume:
        "Le réveil de DIO, repêché du fond de l'océan, éveille des Stands à travers le monde — dont celui de Jotaro. Les Stardust Crusaders traversent le globe pour rejoindre l'Égypte et mettre fin au vampire, au terme de 50 jours de combats.",
      themes: ["Stands", "Tarot", "Dieux égyptiens", "Road trip"],
      casting: ["Jotaro Kujo", "Joseph Joestar", "Mohammed Avdol", "Noriaki Kakyoin", "Jean-Pierre Polnareff", "Iggy", "DIO", "Vanilla Ice"],
      note: "C'est ici que la mécanique des Stands remplace définitivement le Hamon.",
    },
    {
      id: "part4",
      numero: 4,
      titre: "Diamond is Unbreakable",
      titreJp: "ダイヤモンドは砕けない",
      publication: "1992 – 1995",
      epoque: "1999",
      lieu: "Morioh, Japon",
      jojo: "Josuke Higashikata",
      antagoniste: "Yoshikage Kira",
      pouvoir: "Stands",
      couleur: "#0f8b8d",
      accroche: "Une ville entière de Stands et un tueur en série invisible.",
      resume:
        "Morioh, ville paisible, est parcourue par une flèche qui éveille des Stands. Aux côtés de Koichi et Okuyasu, Josuke enquête sur un tueur en série obsédé par les mains : Yoshikage Kira.",
      themes: ["Vie quotidienne", "Enquête", "Morioh", "Flèche"],
      casting: ["Josuke Higashikata", "Koichi Hirose", "Okuyasu Nijimura", "Rohan Kishibe", "Yukako Yamagishi", "Yoshikage Kira", "Jotaro Kujo", "Joseph Joestar"],
      note: "Araki passe d'une épopée mondiale à une intrigue de quartier : un virage stylistique majeur.",
    },
    {
      id: "part5",
      numero: 5,
      titre: "Golden Wind",
      titreJp: "黄金の風",
      publication: "1995 – 1999",
      epoque: "2001",
      lieu: "Italie",
      jojo: "Giorno Giovanna",
      antagoniste: "Diavolo",
      pouvoir: "Stands",
      couleur: "#b8860b",
      accroche: "Un gangster rêveur et le Stand ultime : le Requiem.",
      resume:
        "Giorno Giovanna, fils de DIO, veut réformer la mafia Passione de l'intérieur. Avec l'équipe de Bruno Bucciarati, il remonte la piste du mystérieux Boss et de sa double identité, jusqu'au Stand ultime.",
      themes: ["Mafia", "Passione", "Requiem", "Détermination"],
      casting: ["Giorno Giovanna", "Bruno Bucciarati", "Guido Mista", "Narancia Ghirga", "Pannacotta Fugo", "Leone Abbacchio", "Trish Una", "Diavolo"],
      note: "Considérée par beaucoup de lecteurs comme la partie la plus maîtrisée narrativement.",
    },
    {
      id: "part6",
      numero: 6,
      titre: "Stone Ocean",
      titreJp: "ストーンオーシャン",
      publication: "2000 – 2003",
      epoque: "2011",
      lieu: "Floride, États-Unis",
      jojo: "Jolyne Cujoh",
      antagoniste: "Enrico Pucci",
      pouvoir: "Stands",
      couleur: "#1f7a4d",
      accroche: "La première JoJo : une femme, une prison et la fin d'un univers.",
      resume:
        "Emprisonnée à Green Dolphin Street pour un crime qu'elle n'a pas commis, Jolyne Cujoh, fille de Jotaro, découvre que le prêtre Enrico Pucci œuvre à accomplir le plan de DIO — quitte à faire s'effondrer l'univers lui-même.",
      themes: ["Prison", "Foi", "Accélération", "Fin du monde"],
      casting: ["Jolyne Cujoh", "Hermes Costello", "Narciso Anasui", "Weather Report", "Emporio Alniño", "Enrico Pucci", "Jotaro Kujo", "DIO"],
      note: "La conclusion fait basculer la saga vers un nouvel univers : les parties 7 à 9.",
    },
    {
      id: "part7",
      numero: 7,
      titre: "Steel Ball Run",
      titreJp: "スティール・ボール・ラン",
      publication: "2004 – 2011",
      epoque: "1890",
      lieu: "États-Unis (course transcontinentale)",
      jojo: "Johnny Joestar",
      antagoniste: "Funny Valentine",
      pouvoir: "Spin (rotation)",
      couleur: "#5b3a70",
      accroche: "Une course de chevaux mythique, le Spin et un nouvel univers.",
      resume:
        "Course transcontinentale de 6 000 km à travers les États-Unis. Johnny Joestar, ancien jockey paralysé, et Gyro Zeppeli, maître du Spin, découvrent que la course cache une conspiration d'État autour de morceaux d'un cadavre sacré.",
      themes: ["Spin", "Course", "Cadavre sacré", "Univers alternatif"],
      casting: ["Johnny Joestar", "Gyro Zeppeli", "Diego Brando", "Funny Valentine", "Hot Pants", "Mountain Tim", "Lucy Steel"],
      note: "Premier redémarrage de continuité : la saga bascule dans un univers alternatif.",
    },
    {
      id: "part8",
      numero: 8,
      titre: "JoJolion",
      titreJp: "ジョジョリオン",
      publication: "2011 – 2021",
      epoque: "2011 – 2012",
      lieu: "Morioh (univers alternatif)",
      jojo: "Josuke Higashikata (« Gappy »)",
      antagoniste: "Tooru / Wonder of U",
      pouvoir: "Stands, Spin",
      couleur: "#2a6f97",
      accroche: "Amnésie, fruit Locacaca et malédiction urbaine.",
      resume:
        "Un homme amnésique est retrouvé enfoui près de Morioh et identifié comme « Josuke ». Avec Yasuho Hirose, il cherche son identité — et découvre le fruit Locacaca, capable d'échanger des parties du corps.",
      themes: ["Mémoire", "Locacaca", "Calamité", "Famille Higashikata"],
      casting: ["Josuke Higashikata (« Gappy »)", "Yasuho Hirose", "Norisuke Higashikata IV", "Jobin Higashikata", "Kaato Higashikata", "Tooru"],
      note: "Série la plus longue après Steel Ball Run, avec une narration très cryptique.",
    },
    {
      id: "part9",
      numero: 9,
      titre: "The JOJOLands",
      titreJp: "ザ・ジョジョランズ",
      publication: "2023 – en cours",
      epoque: "Années 2020",
      lieu: "Hawaï, États-Unis",
      jojo: "Jodio Joestar",
      antagoniste: "À découvrir",
      pouvoir: "Stands",
      couleur: "#c2185b",
      accroche: "La partie en cours : un petit gang hawaïen veut devenir riche.",
      resume:
        "Jodio Joestar, lycéen et petit criminel, rêve de devenir riche en vrais dollars. Avec sa sœur Dragona et un équipage improbable, il enchaîne les cambriolages — dont une cible qui dépasse largement son niveau.",
      themes: ["Hawaï", "Braquage", "Volcan", "Gang"],
      casting: ["Jodio Joestar", "Dragona Joestar", "Paco Laburantes", "Usagi Alohaoe", "Meryl Mei Qi", "Charming Man"],
      note: "Série en cours de publication : prudence sur les spoilers dans les discussions.",
    },
  ],

  /**
   * Personnages. `replique` n'est rempli que lorsqu'il s'agit d'une réplique
   * réellement culte et vérifiable ; sinon la fiche s'appuie sur `signature`.
   */
  personnages: [
    { id: "jonathan", nom: "Jonathan Joestar", kanji: "ジョナサン・ジョースター", partie: 1, role: "Protagoniste",
      stand: "Hamon", rejoint: "1880",
      signature: "Le gentleman absolu : générosité, sens de l'honneur, courage physique.",
      replique: null, couleur: "#8c1c3a",
      bio: "Héritier du domaine Joestar, il apprend le Hamon auprès de Zeppeli pour arrêter son frère adoptif devenu vampire." },
    { id: "dio", nom: "Dio Brando", kanji: "ディオ・ブランドー", partie: 1, role: "Antagoniste",
      stand: "The World (partie 3)", rejoint: "1880",
      signature: "L'ambition pure : « Je refuse d'être un simple humain. »",
      replique: "Kono Dio da ! (« C'est moi, Dio ! »)", couleur: "#a8102f",
      bio: "Orphelin recueilli par George Joestar, il se nourrit de rancune et finit par devenir le vampire le plus célèbre du manga." },
    { id: "zeppeli", nom: "Will A. Zeppeli", kanji: "ウィル・A・ツェペリ", partie: 1, role: "Mentor",
      stand: "Hamon", rejoint: "1888",
      signature: "Le maître du Hamon qui enseigne le sacrifice.",
      replique: null, couleur: "#c9a227",
      bio: "Descendant d'une lignée de praticiens du Hamon, il transmet sa technique — et sa volonté — à Jonathan." },
    { id: "speedwagon", nom: "Robert E. O. Speedwagon", kanji: "ロバート・E・O・スピードワゴン", partie: 1, role: "Allié",
      stand: "Aucun", rejoint: "1888",
      signature: "Témoin légendaire de la saga, capable de « sentir » si un homme est bon.",
      replique: null, couleur: "#7d6b54",
      bio: "Ancien gangster de Londres devenu fidèle allié de la famille Joestar, puis fondateur de la Fondation Speedwagon." },

    { id: "joseph", nom: "Joseph Joestar", kanji: "ジョセフ・ジョースター", partie: 2, role: "Protagoniste",
      stand: "Hermit Purple (partie 3)", rejoint: "1938",
      signature: "Bluffeur génial : il court, il prévoit, il gagne.",
      replique: "Ta prochaine réplique sera : … (sa signature)", couleur: "#c2570a",
      bio: "Petit-fils de Jonathan, il mène la guerre contre les Pillar Men et devient le doyen de la famille Joestar." },
    { id: "caesar", nom: "Caesar Anthonio Zeppeli", kanji: "シーザー・アントニオ・ツェペリ", partie: 2, role: "Allié",
      stand: "Hamon", rejoint: "1938",
      signature: "Le Hamon en bulles de savon : élégance et orgueil.",
      replique: null, couleur: "#e0a12d",
      bio: "Petit-fils de Will A. Zeppeli, rival puis ami de Joseph, il maîtrise un Hamon porté par des bulles." },
    { id: "lisa-lisa", nom: "Lisa Lisa", kanji: "リサリサ", partie: 2, role: "Mentor",
      stand: "Hamon", rejoint: "1938",
      signature: "Une maîtresse du Hamon dont la véritable identité est un secret de famille.",
      replique: null, couleur: "#9b2f5f",
      bio: "Gardienne de la Pierre Rouge d'Aja, elle entraîne Joseph et Caesar avec une exigence implacable." },
    { id: "stroheim", nom: "Rudol von Stroheim", kanji: "ルドル・フォン・シュトロハイム", partie: 2, role: "Allié",
      stand: "Aucun (cyborg)", rejoint: "1938",
      signature: "L'officier nazi cyborg converti en allié fanfaron.",
      replique: "BAAAL !", couleur: "#3f6b46",
      bio: "Militaire allemand obsédé par la supériorité de la science, il devient un allié inattendu contre les Pillar Men." },

    { id: "jotaro", nom: "Jotaro Kujo", kanji: "空条承太郎", partie: 3, role: "Protagoniste",
      stand: "Star Platinum", rejoint: "1988",
      signature: "Le calme imperturbable : casquette fondue au crâne et poings les plus rapides du monde.",
      replique: "Yare yare daze… (« Quelle plaie… »)", couleur: "#3b3f8f",
      bio: "Lycéen de 17 ans au caractère taciturne, il traverse le monde pour sauver sa mère de la malédiction de DIO." },
    { id: "kakyoin", nom: "Noriaki Kakyoin", kanji: "花京院典明", partie: 3, role: "Allié",
      stand: "Hierophant Green", rejoint: "1988",
      signature: "Le tacticien : « 20 mètres, c'est ma portée. »",
      replique: "Rerorerorerorerorero…", couleur: "#2f7d6f",
      bio: "Le premier Stand user rencontré par Jotaro, guéri de l'emprise de DIO grâce à Star Platinum." },
    { id: "polnareff", nom: "Jean-Pierre Polnareff", kanji: "ジャン・ピエール・ポルナレフ", partie: 3, role: "Allié",
      stand: "Silver Chariot", rejoint: "1988",
      signature: "L'épéiste français : grande gueule, grand cœur, revanche à prendre.",
      replique: "Hora hora hora !", couleur: "#c0c0c0",
      bio: "Il poursuit l'homme qui a tué sa sœur, puis rejoint les Stardust Crusaders jusqu'en Égypte." },
    { id: "avdol", nom: "Mohammed Avdol", kanji: "モハメド・アヴドゥル", partie: 3, role: "Allié",
      stand: "Magician's Red", rejoint: "1988",
      signature: "Le devin égyptien, voix de la sagesse du groupe.",
      replique: null, couleur: "#d4461f",
      bio: "Expert des Stands et du feu, il sert de mentor technique aux Crusaders et surveille les cartes du Tarot." },
    { id: "iggy", nom: "Iggy", kanji: "イギー", partie: 3, role: "Allié",
      stand: "The Fool", rejoint: "1989",
      signature: "Un chien de gouttière égoïste… et héroïque malgré lui.",
      replique: null, couleur: "#b9a06a",
      bio: "Chien errant recruté de force en Égypte, il déteste les humains avant de se battre à leurs côtés." },
    { id: "vanilla-ice", nom: "Vanilla Ice", kanji: "ヴァニラ・アイス", partie: 3, role: "Antagoniste secondaire",
      stand: "Cream", rejoint: "1989",
      signature: "Le serviteur le plus dévoué (et le plus terrifiant) de DIO.",
      replique: null, couleur: "#4b3f6b",
      bio: "Fanatique de DIO, il se fait décapiter volontairement pour prouver sa loyauté et efface littéralement la matière." },

    { id: "josuke4", nom: "Josuke Higashikata", kanji: "東方仗助", partie: 4, role: "Protagoniste",
      stand: "Crazy Diamond", rejoint: "1999",
      signature: "Le lycéen au cœur tendre : ne critiquez jamais sa coupe de cheveux.",
      replique: "Dora dora dora !", couleur: "#0f8b8d",
      bio: "Fils caché de Joseph Joestar, il possède le pouvoir de réparer et de recomposer la matière — ce qui fait de lui le « médecin » de Morioh." },
    { id: "koichi", nom: "Koichi Hirose", kanji: "広瀬康一", partie: 4, role: "Allié / narrateur",
      stand: "Echoes (Actes 1-3)", rejoint: "1999",
      signature: "Le petit héros qui grandit : d'abord peureux, puis inébranlable.",
      replique: null, couleur: "#3f9e57",
      bio: "Meilleur ami de Josuke, il est aussi la figure morale de la partie 4 et le premier narrateur secondaire réel de la saga." },
    { id: "okuyasu", nom: "Okuyasu Nijimura", kanji: "虹村億泰", partie: 4, role: "Allié",
      stand: "The Hand", rejoint: "1999",
      signature: "La force brute au grand cœur, pas toujours affûtée intellectuellement.",
      replique: null, couleur: "#8a6d3b",
      bio: "Il rejoint Josuke après la mort de son frère Keicho et devient le meilleur soutien du groupe." },
    { id: "rohan", nom: "Rohan Kishibe", kanji: "岸辺露伴", partie: 4, role: "Allié / rival",
      stand: "Heaven's Door", rejoint: "1999",
      signature: "Le mangaka obsessionnel qui puise son art dans la vie réelle — même au prix des autres.",
      replique: null, couleur: "#5a4a86",
      bio: "Auteur à succès de Morioh, il lit les souvenirs puis les réécrit dans le corps de ses « modèles »." },
    { id: "kira", nom: "Yoshikage Kira", kanji: "吉良吉影", partie: 4, role: "Antagoniste",
      stand: "Killer Queen (+ Bites the Dust)", rejoint: "1999",
      signature: "Un tueur en série qui veut seulement vivre tranquille.",
      replique: "Mon nom est Yoshikage Kira. J'ai 33 ans…", couleur: "#c9b8a0",
      bio: "Employé de bureau discret et collectionneur de mains, il est l'antagoniste le plus glaçant de la série." },

    { id: "giorno", nom: "Giorno Giovanna", kanji: "ジョルノ・ジョバァーナ", partie: 5, role: "Protagoniste",
      stand: "Gold Experience → Gold Experience Requiem", rejoint: "2001",
      signature: "Le rêve d'un « Gang-Star » : prendre le pouvoir pour changer la mafia de l'intérieur.",
      replique: "J'ai un rêve, Giorno Giovanna a un rêve.", couleur: "#b8860b",
      bio: "Fils de DIO (via le corps de Jonathan), il grandit à Naples et rejoint Passione pour renverser le Boss." },
    { id: "bucciarati", nom: "Bruno Bucciarati", kanji: "ブローノ・ブチャラティ", partie: 5, role: "Mentor / allié",
      stand: "Sticky Fingers", rejoint: "2001",
      signature: "La résolution incarnée : un chef d'équipe qui ne trahit jamais ses convictions.",
      replique: "Ari ari ari… Arrivederci !", couleur: "#2e6f8f",
      bio: "Capitaine respecté de l'équipe de Naples, il découvre les crimes du Boss et choisit la rébellion." },
    { id: "mista", nom: "Guido Mista", kanji: "グイード・ミスタ", partie: 5, role: "Allié",
      stand: "Sex Pistols (n°1 à 7)", rejoint: "2001",
      signature: "Le gunman superstitieux qui déteste le chiffre 4.",
      replique: null, couleur: "#3f5f8f",
      bio: "Tireur d'élite de l'équipe, il se bat avec une escouade de petits Stands numérotés qui pilotent ses balles — il évite le n°4 par superstition." },
    { id: "narancia", nom: "Narancia Ghirga", kanji: "ナランチャ・ギルガ", partie: 5, role: "Allié",
      stand: "Aerosmith", rejoint: "2001",
      signature: "L'électron libre du groupe : impulsif, fidèle, avide d'apprendre.",
      replique: null, couleur: "#8f3f6f",
      bio: "Ancien enfant des rues recueilli par Bucciarati, il transforme son Aerosmith en radar de combat." },
    { id: "abbacchio", nom: "Leone Abbacchio", kanji: "レオーネ・アバッキオ", partie: 5, role: "Allié",
      stand: "Moody Blues", rejoint: "2001",
      signature: "Le cynique de l'équipe, rongé par la culpabilité.",
      replique: null, couleur: "#5b5b7a",
      bio: "Ancien policier déchu, il utilise Moody Blues pour rejouer le passé et remonter les pistes du Boss." },
    { id: "fugo", nom: "Pannacotta Fugo", kanji: "パンナコッタ・フーゴ", partie: 5, role: "Allié (puis en retrait)",
      stand: "Purple Haze", rejoint: "2001",
      signature: "Le génie colérique dont le Stand est une arme de destruction massive.",
      replique: null, couleur: "#7a3f9b",
      bio: "Étudiant surdoué de 16 ans, il refuse de suivre l'équipe au moment de la trahison — un choix très commenté." },
    { id: "trish", nom: "Trish Una", kanji: "トリッシュ・ウナ", partie: 5, role: "Alliée",
      stand: "Spice Girl", rejoint: "2001",
      signature: "Elle passe de protégée fragile à combattante assumée.",
      replique: null, couleur: "#d16ba5",
      bio: "Fille cachée du Boss, elle découvre son propre Stand et gagne sa place dans l'équipe avant le final." },
    { id: "diavolo", nom: "Diavolo", kanji: "ディアボロ", partie: 5, role: "Antagoniste",
      stand: "King Crimson (+ Epitaph)", rejoint: "2001",
      signature: "Le Boss invisible : il efface les causes et ne laisse que les conséquences.",
      replique: null, couleur: "#7b1c2b",
      bio: "Chef secret de Passione, il œuvre à l'effacement de son propre passé — et de sa fille." },

    { id: "jolyne", nom: "Jolyne Cujoh", kanji: "空条徐倫", partie: 6, role: "Protagoniste",
      stand: "Stone Free", rejoint: "2011",
      signature: "La première JoJo féminine : bagarreuse, têtue, profondément humaine.",
      replique: "Yare yare dawa…", couleur: "#1f7a4d",
      bio: "Fille de Jotaro, elle transforme son corps en fil pour survivre à Green Dolphin Street et sauver son père." },
    { id: "hermes", nom: "Hermes Costello", kanji: "エルメェス・コステロ", partie: 6, role: "Alliée",
      stand: "Kiss", rejoint: "2011",
      signature: "La compagne de cellule qui duplique les objets par autocollants.",
      replique: null, couleur: "#c24b8f",
      bio: "Elle poursuit en prison l'homme responsable de la mort de sa sœur et devient la première alliée de Jolyne." },
    { id: "anasui", nom: "Narciso Anasui", kanji: "ナルシソ・アナスイ", partie: 6, role: "Allié",
      stand: "Diver Down", rejoint: "2011",
      signature: "Un amour obsessionnel transformé en puissance de frappe.",
      replique: null, couleur: "#7f4fa0",
      bio: "Placé en détention pour un meurtre, il tombe amoureux de Jolyne et met Diver Down à son service." },
    { id: "weather", nom: "Weather Report", kanji: "ウェザー・リポート", partie: 6, role: "Allié",
      stand: "Weather Report", rejoint: "2011",
      signature: "L'amnésique le plus dangereux de la prison.",
      replique: null, couleur: "#4fa0c2",
      bio: "Homme sans mémoire enfermé dans l'aile d'isolement, lié malgré lui au plan de Pucci." },
    { id: "pucci", nom: "Enrico Pucci", kanji: "エンリコ・プッチ", partie: 6, role: "Antagoniste",
      stand: "Whitesnake → C-Moon → Made in Heaven", rejoint: "2011",
      signature: "Le prêtre qui veut « atteindre la vérité de l'humanité » en accélérant le monde.",
      replique: null, couleur: "#3a3a4a",
      bio: "Ami et disciple de DIO, il orchestre sa résurrection indirecte via Jolyne pour réinitialiser l'univers." },

    { id: "johnny", nom: "Johnny Joestar", kanji: "ジョニィ・ジョースター", partie: 7, role: "Protagoniste",
      stand: "Tusk (Actes 1-4)", rejoint: "1890",
      signature: "Un ancien prodige paralysé qui apprend à tirer avec ses ongles.",
      replique: null, couleur: "#5b3a70",
      bio: "Ancien jockey de génie handicapé après une agression, il découvre le Spin en touchant les sphères de Gyro." },
    { id: "gyro", nom: "Gyro Zeppeli", kanji: "ジャイロ・ツェペリ", partie: 7, role: "Protagoniste / mentor",
      stand: "Ball Breaker (via le Spin)", rejoint: "1890",
      signature: "Le maître du Spin, à la fois guide et comique de service.",
      replique: null, couleur: "#1f9e8f",
      bio: "Bourreau de naissance devenu cavalier, il court pour sauver la vie d'un enfant et enseigne la Rotation à Johnny." },
    { id: "diego", nom: "Diego Brando", kanji: "ディエゴ・ブランド", partie: 7, role: "Rival / antagoniste",
      stand: "Scary Monsters", rejoint: "1890",
      signature: "Le rival cynique et ambitieux de Steel Ball Run.",
      replique: null, couleur: "#8a6f2b",
      bio: "Jockey surdoué d'origine pauvre, il écrase tout sur son passage pour s'élever socialement." },
    { id: "valentine", nom: "Funny Valentine", kanji: "ファニー・ヴァレンタイン", partie: 7, role: "Antagoniste",
      stand: "D4C (Dirty Deeds Done Dirt Cheap)", rejoint: "1890",
      signature: "Le patriotisme absolu : tout sacrifier pour la nation.",
      replique: null, couleur: "#c9c05a",
      bio: "23e président des États-Unis, il veut rassembler les reliques du Cadavre pour faire de son pays la première puissance du monde." },

    { id: "gappy", nom: "Josuke Higashikata « Gappy »", kanji: "東方定助", partie: 8, role: "Protagoniste",
      stand: "Soft & Wet", rejoint: "2011",
      signature: "Un amnésique qui « prend » des choses : friction, son, vue, souvenirs.",
      replique: null, couleur: "#2a6f97",
      bio: "Homme exhumé avec deux corps fusionnés en lui, il cherche son identité au sein de la famille Higashikata." },
    { id: "yasuho", nom: "Yasuho Hirose", kanji: "広瀬康穂", partie: 8, role: "Alliée / co-protagoniste",
      stand: "Paisley Park", rejoint: "2011",
      signature: "La narratrice sensible qui relie Gappy au monde.",
      replique: null, couleur: "#d17fa5",
      bio: "Étudiante rencontrée à Morioh, elle aide l'amnésique à retrouver son passé tout en découvrant sa propre famille." },
    { id: "tooru", nom: "Tooru", kanji: "透龍", partie: 8, role: "Antagoniste",
      stand: "Wonder of U", rejoint: "2012",
      signature: "L'incarnation du « flux » : poursuivre quelqu'un attire la calamité sur soi.",
      replique: null, couleur: "#4f6f8f",
      bio: "Médecin énigmatique lié au fruit Locacaca et adversaire final de JoJolion." },

    { id: "jodio", nom: "Jodio Joestar", kanji: "ジョディオ・ジョースター", partie: 9, role: "Protagoniste",
      stand: "November Rain", rejoint: "2023",
      signature: "Un lycéen hawaïen qui déteste les héros et veut simplement l'argent.",
      replique: null, couleur: "#c2185b",
      bio: "Antihéros assumé de The JOJOLands, il met November Rain et sa pluie de gouttes pesantes au service de ses braquages." },
    { id: "dragona", nom: "Dragona Joestar", kanji: "ドラゴナ・ジョースター", partie: 9, role: "Allié / grande sœur",
      stand: "Smooth Operators", rejoint: "2023",
      signature: "Le sang-froid du duo, capable de déplacer les choses sans les toucher.",
      replique: null, couleur: "#7f4fd1",
      bio: "Grande sœur de Jodio et employée de la bijouterie de Meryl Mei Qi, elle gère les plans les plus risqués." },
    { id: "paco", nom: "Paco Laburantes", kanji: "パコ・ラブランテス", partie: 9, role: "Allié",
      stand: "The Hustle", rejoint: "2023",
      signature: "Le costaud du gang, qui gonfle ses muscles grâce à son propre Stand.",
      replique: null, couleur: "#8f6f3f",
      bio: "Lycéen et délinquant de Hawaï, il rejoint l'équipage pour empocher sa part du butin." },
  ],

  /**
   * Stands. `stats` suit l'échelle A → E des fiches de l'auteur pour les six
   * paramètres canoniques. Un grade `null` affiche « — » (cas des Stands
   * dont la fiche officielle reste vide parce qu'ils sont hors échelle).
   */
  stands: [
    { id: "star-platinum", nom: "Star Platinum", utilisateur: "Jotaro Kujo", partie: 3, type: "Proche portée",
      cri: "ORA ORA ORA !", ref: "Carte du Tarot « L'Étoile »",
      pouvoir: "Force, vitesse et précision surhumaines ; vision et souffle surdéveloppés ; arrêt du temps (révélé en partie 3 puis prolongé en partie 4-6).",
      stats: { puissance: "A", vitesse: "A", portee: "C", persistance: "A", precision: "A", potentiel: "A" } },
    { id: "the-world", nom: "The World", utilisateur: "DIO", partie: 3, type: "Proche portée",
      cri: "MUDA MUDA MUDA !", ref: "Carte du Tarot « Le Monde »",
      pouvoir: "Jumeau de Star Platinum : il arrête le temps jusqu'à 9 secondes, en plus d'une force colossale.",
      stats: { puissance: "A", vitesse: "A", portee: "C", persistance: "B", precision: "B", potentiel: "A" } },
    { id: "hierophant-green", nom: "Hierophant Green", utilisateur: "Noriaki Kakyoin", partie: 3, type: "Moyenne portée",
      cri: "—", ref: "Carte du Tarot « Le Hiérophante »",
      pouvoir: "Corps extensible en fils et émeraudes projetées : le Stand parfait pour le combat à distance contrôlée.",
      stats: { puissance: "C", vitesse: "B", portee: "A", persistance: "B", precision: "C", potentiel: "C" } },
    { id: "silver-chariot", nom: "Silver Chariot", utilisateur: "Jean-Pierre Polnareff", partie: 3, type: "Proche portée",
      cri: "Hora hora hora !", ref: "Carte du Tarot « Le Chariot »",
      pouvoir: "Escrimeur en armure accéléré au point de créer des leurres ; sans armure, la vitesse devient folle.",
      stats: { puissance: "C", vitesse: "A", portee: "C", persistance: "B", precision: "C", potentiel: "C" } },
    { id: "magicians-red", nom: "Magician's Red", utilisateur: "Mohammed Avdol", partie: 3, type: "Moyenne portée",
      cri: "—", ref: "Carte du Tarot « Le Magicien »",
      pouvoir: "Pyrokinésie : flamme libre, croix de feu et détection thermique des ennemis invisibles.",
      stats: { puissance: "B", vitesse: "B", portee: "C", persistance: "B", precision: "C", potentiel: "C" } },
    { id: "the-fool", nom: "The Fool", utilisateur: "Iggy", partie: 3, type: "Proche portée",
      cri: "—", ref: "Carte du Tarot « Le Mat »",
      pouvoir: "Sable vivant qui prend la forme d'un loup, d'un planeur ou d'un bouclier, manipulable librement.",
      stats: { puissance: "B", vitesse: "C", portee: "D", persistance: "B", precision: "D", potentiel: "C" } },
    { id: "hermit-purple", nom: "Hermit Purple", utilisateur: "Joseph Joestar", partie: 3, type: "Moyenne portée",
      cri: "—", ref: "Carte du Tarot « L'Ermite »",
      pouvoir: "Vignes de Hamon qui se connectent aux objets et téléchargent des images : photographie spirituelle.",
      stats: { puissance: "E", vitesse: "C", portee: "C", persistance: "B", precision: "C", potentiel: "D" } },
    { id: "cream", nom: "Cream", utilisateur: "Vanilla Ice", partie: 3, type: "Proche portée",
      cri: "—", ref: "Carte du Tarot « La Maison-Dieu » (groupe Cream)",
      pouvoir: "Vortex d'effacement qui envoie dans une dimension inconnue tout ce qu'il touche, l'utilisateur compris.",
      stats: { puissance: "B", vitesse: "B", portee: "D", persistance: "C", precision: "D", potentiel: "D" } },

    { id: "crazy-diamond", nom: "Crazy Diamond", utilisateur: "Josuke Higashikata", partie: 4, type: "Proche portée",
      cri: "DORA DORA DORA !", ref: "Pink Floyd — « Shine On You Crazy Diamond »",
      pouvoir: "Restauration : il répare et recompose la matière (y compris les blessures), mais ne peut pas se soigner lui-même.",
      stats: { puissance: "A", vitesse: "A", portee: "C", persistance: "B", precision: "B", potentiel: "C" } },
    { id: "the-hand", nom: "The Hand", utilisateur: "Okuyasu Nijimura", partie: 4, type: "Proche portée",
      cri: "—", ref: "Référence musicale non documentée (Stand de la partie 4)",
      pouvoir: "Efface l'espace entre deux points : ce qui est « gratté » disparaît purement et simplement.",
      stats: { puissance: "B", vitesse: "A", portee: "D", persistance: "B", precision: "C", potentiel: "C" } },
    { id: "echoes-act3", nom: "Echoes ACT3", utilisateur: "Koichi Hirose", partie: 4, type: "Longue portée",
      cri: "—", ref: "Pink Floyd — « Echoes »",
      pouvoir: "Troisième forme d'Echoes : le poids « 3 FREEZE » colle un adversaire au sol en le surchargeant.",
      stats: { puissance: "A", vitesse: "B", portee: "C", persistance: "B", precision: "B", potentiel: "C" } },
    { id: "heavens-door", nom: "Heaven's Door", utilisateur: "Rohan Kishibe", partie: 4, type: "Proche portée",
      cri: "—", ref: "Bob Dylan — « Knockin' on Heaven's Door »",
      pouvoir: "Transforme une personne en livre : on peut lire ses souvenirs puis y écrire des ordres irrésistibles.",
      stats: { puissance: "E", vitesse: "C", portee: "C", persistance: "A", precision: "A", potentiel: "A" } },
    { id: "killer-queen", nom: "Killer Queen", utilisateur: "Yoshikage Kira", partie: 4, type: "Proche portée",
      cri: "—", ref: "Queen — « Killer Queen »",
      pouvoir: "Transforme tout objet touché en bombe ; Sheer Heart Attack et Bites the Dust en sont des extensions.",
      stats: { puissance: "B", vitesse: "B", portee: "D", persistance: "B", precision: "A", potentiel: "B" } },

    { id: "gold-experience", nom: "Gold Experience", utilisateur: "Giorno Giovanna", partie: 5, type: "Proche portée",
      cri: "MUDA MUDA MUDA !", ref: "Prince — album « The Gold Experience »",
      pouvoir: "Donne la vie à la matière inerte et accélère les sensations : les dégâts arrivent « après » l'impact ressenti.",
      stats: { puissance: "B", vitesse: "A", portee: "C", persistance: "B", precision: "A", potentiel: "A" } },
    { id: "gold-experience-requiem", nom: "Gold Experience Requiem", utilisateur: "Giorno Giovanna", partie: 5, type: "Évolution / ultime",
      cri: "MUDA MUDA MUDA !", ref: "Prince — album « The Gold Experience »",
      pouvoir: "Annule toute volonté et tout résultat : il ramène l'adversaire à un état « zéro » sans fin, en boucle infinie.",
      stats: { puissance: null, vitesse: null, portee: null, persistance: null, precision: null, potentiel: null } },
    { id: "king-crimson", nom: "King Crimson", utilisateur: "Diavolo", partie: 5, type: "Proche portée",
      cri: "—", ref: "King Crimson — groupe culte",
      pouvoir: "Efface le temps : il coupe un intervalle de quelques secondes et ne laisse que les conséquences aux autres.",
      stats: { puissance: "A", vitesse: "A", portee: "C", persistance: "B", precision: "B", potentiel: "C" } },
    { id: "sticky-fingers", nom: "Sticky Fingers", utilisateur: "Bruno Bucciarati", partie: 5, type: "Proche portée",
      cri: "ARI ARI ARI !", ref: "The Rolling Stones — « Sticky Fingers »",
      pouvoir: "Ouvre des fermetures éclair dans tout ce qu'il touche : murs, corps, corps humains, et l'espace lui-même.",
      stats: { puissance: "A", vitesse: "A", portee: "D", persistance: "A", precision: "B", potentiel: "C" } },
    { id: "sex-pistols", nom: "Sex Pistols", utilisateur: "Guido Mista", partie: 5, type: "Longue portée",
      cri: "—", ref: "Sex Pistols — groupe punk",
      pouvoir: "Escouade de petites entités numérotées qui pilotent les balles de Mista en vol et corrigent leur trajectoire.",
      stats: { puissance: "E", vitesse: "A", portee: "C", persistance: "A", precision: "A", potentiel: "C" } },
    { id: "purple-haze", nom: "Purple Haze", utilisateur: "Pannacotta Fugo", partie: 5, type: "Proche portée",
      cri: "—", ref: "Jimi Hendrix — « Purple Haze »",
      pouvoir: "Sécrète un virus qui dissout la chair en 30 secondes. Son utilisateur ne le contrôle qu'à moitié.",
      stats: { puissance: "A", vitesse: "B", portee: "C", persistance: "D", precision: "D", potentiel: "B" } },
    { id: "spice-girl", nom: "Spice Girl", utilisateur: "Trish Una", partie: 5, type: "Proche portée",
      cri: "—", ref: "Spice Girls — groupe pop",
      pouvoir: "Ramollit toute matière à l'extrême : un mur devient élastique, un fil d'acier devient une corde molle.",
      stats: { puissance: "A", vitesse: "B", portee: "C", persistance: "A", precision: "B", potentiel: "C" } },

    { id: "stone-free", nom: "Stone Free", utilisateur: "Jolyne Cujoh", partie: 6, type: "Proche portée",
      cri: "ORA ORA ORA !", ref: "Jimi Hendrix — « Stone Free »",
      pouvoir: "Déroule son corps en fil : il peut espionner, ligoter, se coudre ou tisser un filet piégeur.",
      stats: { puissance: "B", vitesse: "B", portee: "C", persistance: "A", precision: "B", potentiel: "B" } },
    { id: "kiss", nom: "Kiss", utilisateur: "Hermes Costello", partie: 6, type: "Proche portée",
      cri: "—", ref: "Kiss — groupe de rock",
      pouvoir: "Colle un autocollant qui crée un double imparfait de l'objet : la réunion des deux produit un choc destructeur.",
      stats: { puissance: "B", vitesse: "B", portee: "C", persistance: "B", precision: "D", potentiel: "C" } },
    { id: "diver-down", nom: "Diver Down", utilisateur: "Narciso Anasui", partie: 6, type: "Proche portée",
      cri: "—", ref: "Van Halen — « Diver Down »",
      pouvoir: "Plonge dans les objets et les corps pour les démonter, y compris de l'intérieur.",
      stats: { puissance: "A", vitesse: "B", portee: "C", persistance: "B", precision: "C", potentiel: "B" } },
    { id: "weather-report", nom: "Weather Report", utilisateur: "Weather Report", partie: 6, type: "Longue portée",
      cri: "—", ref: "Weather Report — groupe de jazz fusion",
      pouvoir: "Contrôle la météo sur une zone entière : nuages, tornades, pluie de grenouilles, ozone pur.",
      stats: { puissance: "B", vitesse: "B", portee: "A", persistance: "B", precision: "E", potentiel: "A" } },
    { id: "whitesnake", nom: "Whitesnake", utilisateur: "Enrico Pucci", partie: 6, type: "Moyenne portée",
      cri: "—", ref: "Whitesnake — groupe de hard rock",
      pouvoir: "Extrait le « DISC » d'un être vivant : sa mémoire et/ou son Stand deviennent des disques volables.",
      stats: { puissance: "B", vitesse: "B", portee: "C", persistance: "B", precision: "C", potentiel: "A" } },
    { id: "made-in-heaven", nom: "Made in Heaven", utilisateur: "Enrico Pucci", partie: 6, type: "Évolution / ultime",
      cri: "—", ref: "Queen — « Made in Heaven »",
      pouvoir: "Accélère le temps jusqu'à la fin de l'univers pour en créer un nouveau, où seul Pucci garde sa mémoire.",
      stats: { puissance: null, vitesse: null, portee: null, persistance: null, precision: null, potentiel: null } },

    { id: "tusk-act4", nom: "Tusk ACT4", utilisateur: "Johnny Joestar", partie: 7, type: "Évolution / ultime",
      cri: "—", ref: "Fleetwood Mac — « Tusk »",
      pouvoir: "Tire des ongles chargés de la Rotation dorée infinie : la blessure poursuit la cible à jamais, même entre les dimensions.",
      stats: { puissance: "A", vitesse: "A", portee: "C", persistance: "A", precision: "A", potentiel: "A" } },
    { id: "ball-breaker", nom: "Ball Breaker", utilisateur: "Gyro Zeppeli", partie: 7, type: "Évolution / ultime",
      cri: "—", ref: "Fleetwood Mac — « Tusk » (thème du Spin)",
      pouvoir: "Manifestation quasi-Stand de la Rotation parfaite enseignée par la famille Zeppeli ; elle frappe le corps au-delà de l'armure.",
      stats: { puissance: "A", vitesse: "B", portee: "C", persistance: "C", precision: "B", potentiel: "B" } },
    { id: "d4c", nom: "D4C", utilisateur: "Funny Valentine", partie: 7, type: "Proche portée",
      cri: "—", ref: "AC/DC — « Dirty Deeds Done Dirt Cheap »",
      pouvoir: "Voyage entre dimensions parallèles : il peut amener des doubles de lui-même et d'objets, au prix d'une règle brutale.",
      stats: { puissance: "B", vitesse: "A", portee: "C", persistance: "B", precision: "B", potentiel: "A" } },
    { id: "scary-monsters", nom: "Scary Monsters", utilisateur: "Diego Brando", partie: 7, type: "Proche portée",
      cri: "—", ref: "David Bowie — « Scary Monsters (and Super Creeps) »",
      pouvoir: "Transforme son utilisateur et ses victimes en dinosaures rapides et sensibles aux odeurs.",
      stats: { puissance: "B", vitesse: "A", portee: "C", persistance: "B", precision: "C", potentiel: "B" } },

    { id: "soft-and-wet", nom: "Soft & Wet", utilisateur: "Josuke « Gappy »", partie: 8, type: "Proche portée",
      cri: "—", ref: "Prince — « Soft and Wet »",
      pouvoir: "Des bulles qui « prennent » une propriété (friction, son, vue, humidité) et la dérobent à sa cible.",
      stats: { puissance: "B", vitesse: "B", portee: "C", persistance: "B", precision: "B", potentiel: "B" } },
    { id: "paisley-park", nom: "Paisley Park", utilisateur: "Yasuho Hirose", partie: 8, type: "Longue portée",
      cri: "—", ref: "Prince — « Paisley Park »",
      pouvoir: "Guide son utilisatrice en lui montrant chemins et informations : un GPS de la vérité, très peu offensif.",
      stats: { puissance: "E", vitesse: "C", portee: "A", persistance: "B", precision: "C", potentiel: "C" } },
    { id: "wonder-of-u", nom: "Wonder of U", utilisateur: "Tooru", partie: 8, type: "Évolution / ultime",
      cri: "—", ref: "The Rolling Stones — « Wonder of U » (inspiré)",
      pouvoir: "« Le flux » : toute tentative de poursuivre l'utilisateur déclenche une calamité proportionnelle.",
      stats: { puissance: null, vitesse: null, portee: null, persistance: null, precision: null, potentiel: null } },

    { id: "november-rain", nom: "November Rain", utilisateur: "Jodio Joestar", partie: 9, type: "Moyenne portée",
      cri: "—", ref: "Guns N' Roses — « November Rain »",
      pouvoir: "Fait tomber une pluie de gouttes d'une masse énorme, capable de percer ou d'écraser ce qu'elle touche.",
      stats: { puissance: "A", vitesse: "B", portee: "B", persistance: "B", precision: "C", potentiel: "B" } },
    { id: "smooth-operators", nom: "Smooth Operators", utilisateur: "Dragona Joestar", partie: 9, type: "Moyenne portée",
      cri: "—", ref: "Sade — « Smooth Operator »",
      pouvoir: "Déplace et déforme la matière sans la toucher : parfait pour fouiller, ouvrir et faire disparaître les preuves.",
      stats: { puissance: "E", vitesse: "C", portee: "B", persistance: "B", precision: "B", potentiel: "C" } },
    { id: "the-hustle", nom: "The Hustle", utilisateur: "Paco Laburantes", partie: 9, type: "Proche portée",
      cri: "—", ref: "Van McCoy — « The Hustle »",
      pouvoir: "Gonfle les muscles de son utilisateur en démultipliant sa propre masse corporelle.",
      stats: { puissance: "B", vitesse: "C", portee: "E", persistance: "C", precision: "E", potentiel: "C" } },
  ],

  /** Quiz : `bonne` est l'index (0-3) de la bonne réponse dans `options`. */
  quiz: [
    { question: "Dans quelle partie les Stands font-ils leur première apparition ?",
      options: ["Phantom Blood", "Battle Tendency", "Stardust Crusaders", "Diamond is Unbreakable"], bonne: 2,
      explication: "Les Stands apparaissent en partie 3 (1989), remplaçant le Hamon comme système de combat principal." },
    { question: "Quel pouvoir est utilisé par Jonathan et Joseph Joestar ?",
      options: ["Le Spin", "Le Hamon (Onde)", "Les Stands", "Le Locacaca"], bonne: 1,
      explication: "Le Hamon, ou Onde, est une énergie issue de la respiration maîtrisée ; le Spin n'arrive qu'en partie 7." },
    { question: "Qui est l'auteur de JoJo's Bizarre Adventure ?",
      options: ["Masashi Kishimoto", "Hirohiko Araki", "Tite Kubo", "Eiichiro Oda"], bonne: 1,
      explication: "Hirohiko Araki publie la série depuis 1987 dans le Weekly Shōnen Jump, puis dans Ultra Jump." },
    { question: "Quel est le Stand de Josuke Higashikata dans la partie 4 ?",
      options: ["The Hand", "Echoes", "Crazy Diamond", "Heaven's Door"], bonne: 2,
      explication: "Crazy Diamond restaure les objets et les corps — mais Josuke ne peut pas s'en servir sur lui-même." },
    { question: "Dans quelle ville se déroule Diamond is Unbreakable ?",
      options: ["Morioh", "Naples", "Green Dolphin Street", "Aja"], bonne: 0,
      explication: "Morioh est une ville fictive inspirée du Sendai natal d'Araki ; on la retrouve aussi dans JoJolion." },
    { question: "À quel cri de combat associe-t-on Star Platinum ?",
      options: ["MUDA MUDA MUDA !", "ARI ARI ARI !", "ORA ORA ORA !", "HORA HORA HORA !"], bonne: 2,
      explication: "« ORA ORA ORA » est le cri de Star Platinum ; « MUDA » est celui de The World et de Gold Experience." },
    { question: "Qui est la protagoniste de Stone Ocean ?",
      options: ["Hermes Costello", "Trish Una", "Jolyne Cujoh", "Yasuho Hirose"], bonne: 2,
      explication: "Jolyne Cujoh, fille de Jotaro, est la première femme protagoniste de la saga (partie 6)." },
    { question: "Quelle partie raconte une course de chevaux transcontinentale aux États-Unis ?",
      options: ["Steel Ball Run", "Golden Wind", "Battle Tendency", "The JOJOLands"], bonne: 0,
      explication: "Steel Ball Run (partie 7) se déroule en 1890, dans un univers alternatif, autour d'une course de 6 000 km." },
    { question: "Combien de paramètres compte la fiche officielle d'un Stand ?",
      options: ["4", "5", "6", "8"], bonne: 2,
      explication: "Puissance, Vitesse, Portée, Persistance, Précision, Potentiel de développement — notés de A à E." },
    { question: "Quel Stand peut voyager entre les univers parallèles ?",
      options: ["D4C", "King Crimson", "Tusk ACT4", "Whitesnake"], bonne: 0,
      explication: "D4C (Dirty Deeds Done Dirt Cheap) est le Stand du président Funny Valentine, en partie 7." },
  ],

  /** Données du générateur de nom de Stand (fun, 100 % local & déterministe). */
  generateur: {
    prefixes: ["Velvet", "Neon", "Cobalt", "Thunder", "Obsidian", "Paper", "Iron", "Glass", "Midnight", "Blazing",
               "Electric", "Marble", "Hollow", "Golden", "Broken", "Silent", "Crimson", "Turquoise", "Solar", "Feral"],
    suffixes: ["Requiem", "Funk", "Marmalade", "Cassette", "Machine", "Parade", "Sermon", "Mirage", "Carburetor", "Harmonica",
               "Confetti", "Halo", "Quicksand", "Jukebox", "Antenna", "Pistol", "Lullaby", "Switchblade", "Cathedral", "Weather"],
    types: ["Proche portée", "Moyenne portée", "Longue portée", "Évolution / ultime"],
    cris: ["ORA ORA ORA !", "MUDA MUDA MUDA !", "DORA DORA DORA !", "ARI ARI ARI !", "RERO RERO RERO !", "HORA HORA HORA !"],
    pouvoirs: [
      "Manipule le poids de n'importe quel objet du regard.",
      "Transforme les souvenirs en objets physiques que l'on peut voler.",
      "Crée des portes invisibles vers un même instant passé.",
      "Échange la position de deux choses symétriques à l'écran.",
      "Absorbe le son d'une pièce pour le restituer en onde de choc.",
      "Coud deux espaces différents à l'aide d'une aiguille d'air.",
      "Ralentit la douleur : la victime ne sent le coup que 10 secondes plus tard.",
      "Fait pousser des échos de cristal qui répètent les mouvements.",
      "Dévie la trajectoire de tout projectile qui vise son utilisateur.",
      "Efface une seconde de la mémoire collective autour de lui.",
      "Consomme la chance de la cible pour nourrir sa propre vitesse.",
      "Change la couleur d'une matière — et la propriété qui va avec.",
    ],
  },
};

// Exposé explicitement : les scripts classiques vivent dans la portée globale.
// (navigateur → window, Node → globalThis, pour permettre les outils de contrôle)
if (typeof window !== "undefined") window.JJBA_DATA = JJBA_DATA;
else if (typeof globalThis !== "undefined") globalThis.JJBA_DATA = JJBA_DATA;
